### ISSUE TITLE
Complete Version 1

### ISSUE THREAD

**Issue by Michielu** [Michielu/cy-sliding-puzzle#2]
- [x] split images #3 
- [x]  Generate number of moves #4
- [x]  Generate score #4
- [x] Final page format #5
- [x] Populate Square array #6 
- [x] Update number in square #7

**Comment by amupitan** [comment]
Closed by this [commit](https://github.com/Michielu/cy-sliding-puzzle/commit/a05bd26ca49d0617ff3c8b21cc5dce7441a975e4)
